  - name: Update the python-tripleoclient package 
    shell: |
        sudo yum update -y python-tripleoclient
      
  - name: Upgrade director
    shell: |
        openstack undercloud upgrade -y --log-file undercloud_minor_upgrade.log

  - name: Reboot approve 
    pause:
      prompt: Please approve undercloud reboot! Press return to continue. Press Ctrl+c and then "a" to abort

  - name: Reboot after upgrade NIC names
    ansible.builtin.reboot:
      test_command: uptime
    become: yes
    become_user: root
  - debug: msg="Undercloud was restarted successfully"
