---
- name: "backup undercloud"
  become_user: root
  hosts: undercloud

  roles:
    - backup-undercloud-conf

- name: "copy files to nginx"
  become_user: root
  hosts: undercloud

  roles:
    - copy-archive
