---
#- name: "backup undercloud"
#  become_user: root
#  hosts: undercloud

#  roles:
#    - backup-director
 
- name: "check backup"
  become_user: root
  hosts: testing
  
  roles:
    - check-backup
