- name: Test Keystone
  hosts: undercloud
  vars_files:
    - defaults/healthchecks-vars.yml
  tasks:
    - name: Authenticate to the cloud and retrieve the service catalog
      openstack.cloud.auth:
        cloud: default
        interface: internal

    - name: Show service catalog
      debug:
        var: service_catalog
