    - name: Archive undercloud-backup
      shell: sudo tar -czvf /tmp/undercloud-backup.tar.gz /etc/*
      
    - name: Copy to local vm 
      fetch: 
        src: /tmp/undercloud-backup.tar.gz
        dest: /opt/archives/undercloud-backup.tar.gz

    - name: Remove archive
      shell: |
        sudo rm -rf /tmp/undercloud-backup.tar.gz

    - name: Archive stack files
      shell: |
        sudo tar -czvf /tmp/stack.tar.gz /home/stack/

    - name: Copy to local vm
      fetch: 
        src: /tmp/stack.tar.gz
        dest: /opt/archives/stack.tar.gz

    - name: Remove archive
      shell: |
        sudo rm -rf /tmp/stack.tar.gz
