  - name: Start tests
    ansible.builtin.shell: npx playwright test
    args:
      chdir: /opt/openstack-testing
    register: results
  - debug:
      var: results.stdout_lines

  - name: Allure generate results
    shell: |
      PATH=/opt/allure-commandline/allure-2.21.0/bin:$PATH
      allure generate allure-results --clean
    register: results
  - debug:
      var: results.stdout_lines

  - name: Allure open allure-report
    shell: |
      PATH=/opt/allure-commandline/allure-2.21.0/bin:$PATH
      allure serve -p 32000
    register: results
  - debug:
      var: results.stdout_lines
