  - name: Overcloud update preparation
    shell: |
        source ~/stackrc
        openstack overcloud update prepare --templates -e /home/stack/templates/overcloud_images.yaml -e /home/stack/templates/updates-environment.yaml --stack overcloud
 
  - name: Overcloud update
    shell: |
        source ~/stackrc
        openstack overcloud update run --nodes Controller    
