#  - name: Overcloud update preparation
#    shell: |
#        source ~/stackrc
#        openstack overcloud update prepare --templates -e /home/stack/templates/overcloud_images.yaml -e /home/stack/templates/updates-environment.yaml --stack overcloud --ntp-server 10.165.3.1
#    register: results
#  - debug:
#      var: results.stdout_lines
      
  - name: Create fix for network
    shell: |
        source ~/stackrc
        touch fix-network.yaml
        
  - name: Edit network fix playbook
    ansible.builtin.blockinfile:
      path: /home/stack/fix-network.yaml
      block: |2
        - hosts: all
          gather_facts: false
          tasks:
            - name: Add defroute
              ansible.builtin.lineinfile:
                path: /etc/sysconfig/network-scripts/ifcfg-eth1
                line:
                  DEFROUTE=yes
              become: true
              
            - name: Add defroute 2
              ansible.builtin.blockinfile:
                path: /etc/sysconfig/network-scripts/ifcfg-eth0
                block: |
                  DEFROUTE=no
              become: true
 
            - name: Add defroute 3
              ansible.builtin.blockinfile:
                path: /etc/sysconfig/network-scripts/ifcfg-br-ex
                block: |
                  DEFROUTE=no
              become: true
              
            - name: Restart network
              shell: |
                systemctl restart network
              become: true

  - name: Run playbook
    shell: |
        source ~/stackrc
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook -i ~/inventory.yaml -f 20 ~/fix-network.yaml --limit Controller >> ansible-update-network.log

  - name: Overcloud update
    shell: |
        source ~/stackrc
        openstack overcloud update run --nodes Controller    
    register: results
  - debug:
      var: results.stdout_lines
