
    - name: Disable OpenStack Services
      shell: |
        sudo systemctl stop 'openstack-*' httpd haproxy mariadb 'rabbitmq*' docker xinetd

    - name: Install rear
      shell: |
        sudo yum install rear -y
    
    - name: Remove Previous Conf
      shell: |
        sudo rm -rf /etc/rear/local.conf
    
    - name: Create new file
      shell: sudo touch /etc/rear/local.conf
        
    - name: Run backup task
      ansible.builtin.blockinfile:
        path: /etc/rear/local.conf
        block: |
          OUTPUT=ISO
          OUTPUT_URL=nfs://92.204.53.126/nfs
          BACKUP=NETFS
          BACKUP_URL=nfs://92.204.53.126/nfs
          BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
          NETFS_KEEP_OLD_BACKUP_COPY
