    - name: Show backup files
      shell: |
        ls -sh /nfs/director/
      register: results
    - debug:
        var: results.stdout_lines     

    - name: Tail backup log
      shell: |
        tail -n 5 /nfs/director/backup.log
      register: results
    - debug:
        var: results.stdout_lines     
