#    - name: Register subscription
#      shell: |
#        sudo subscription-manager register --username envops --password 'Unix_11!'
#        sudo subscription-manager attach --pool='2c94dfeb8650d275018674dcfcc007f2'
#        sudo subscription-manager repos --disable=*
#        sudo subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms --enable=rhel-7-server-openstack-13-rpms

    - name: Install rear
      shell: sudo yum install rear -y
      
    - name: Remove previous configuration
      shell: sudo rm -rf /etc/rear/local.conf

    - name: Create conf file
      shell: sudo touch /etc/rear/local.conf
      
    - name: Insert new conf
      become: yes 
      ansible.builtin.blockinfile:
        path: /etc/rear/local.conf
        block: |
          OUTPUT=ISO
          OUTPUT_URL=nfs://10.165.3.1/storage
          BACKUP=NETFS
          BACKUP_URL=nfs://10.165.3.1/storage
          BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
          NETFS_KEEP_OLD_BACKUP_COPY=

    - name: Standby node
      shell: sudo pcs node standby overcloud-controller-0
      
    - name: Stop docker
      become: yes
      shell: sudo docker stop $(sudo docker ps -aq)
      
    - name: Run backup
      shell: sudo rear -d -v mkbackup
      
    - name: Unstandby node
      shell: sudo pcs node unstandby overcloud-controller-0

    - name: Reboot after backup
      ansible.builtin.reboot:
        test_command: uptime
      become: yes
    - debug: msg="Controller0 was restarted successfully"
