#    - name: Register subscription
#      shell: |
#        sudo subscription-manager register --username envops --password 'Unix_11!'
#        sudo subscription-manager attach --pool='2c94dfeb8650d275018674dcfcc007f2'
#        sudo subscription-manager repos --disable=*
#        sudo subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms --enable=rhel-7-server-openstack-13-rpms

    - name: Install rear
      shell: sudo yum install rear -y
      
    - name: Remove previous configuration
      shell: sudo rm -rf /etc/rear/local.conf

    - name: Insert new conf
      ansible.builtin.blockinfile:
        path: /etc/rear/local.conf
        block: |
          OUTPUT=ISO
          OUTPUT_URL=nfs://192.168.56.1/storage
          BACKUP=NETFS
          BACKUP_URL=nfs://192.168.56.1/storage
          BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
          NETFS_KEEP_OLD_BACKUP_COPY=
