  - name: Updating your container image source
    shell: |
        source ~/stackrc
        sudo docker login registry.redhat.io --username envops --password 'Unix_11!'
        sudo openstack overcloud container image prepare --namespace=registry.redhat.io/rhosp13 --prefix=openstack- --tag-from-label {version}-{release} --output-env-file=/home/stack/templates/overcloud_images.yaml
    register: results_overcloud_images
  - debug:
      var: results_overcloud_images.stdout_lines
      
  - name: Replace container source
    replace:
      path: /home/stack/templates/overcloud_images.yaml
      regexp: 'registry.redhat.io'
      replace: '10.165.3.14:8787'

  - name: Insert docker credentionals 
    ansible.builtin.blockinfile:
      path: /home/stack/templates/overcloud_images.yaml
      block: |2
          ContainerImageRegistryLogin: true
          ContainerImageRegistryCredentials:
            registry.redhat.io:
              envops: 'Unix_11!'

  - name: Show overcloud_images.yaml
    shell: |
        cat /home/stack/templates/overcloud_images.yaml
    register: results_overcloud_images
  - debug:
      var: results_overcloud_images.stdout_lines

  - name: Verify validation results
    pause:
      seconds: 10
      prompt: Please check overcloud_images.yaml! Press return to continue. Press Ctrl+c and then "a" to abort
